// 한국어 문구 — SPEC §2·§3 의 문구와 웹 src/i18nStrings.js(ko) 에서 가져온 것.
// 세 플랫폼이 같은 문구를 써야 하므로(SPEC §6-6) 화면 코드에 리터럴을 쓰지 않는다.

export const copy = {
  tabs: {
    gallery: "갤러리",
    filter: "필터",
    camera: "카메라",
    photos: "내 사진",
    profile: "프로필",
  },
  home: {
    featured: "추천",
    newest: "새로 나왔어요",
    all: "전체",
    more: "더보기",
    loadFail: "컨셉을 불러오지 못했어요",
  },
  options: {
    myPhoto: "내 사진",
    useRegistered: "등록된 사진 사용",
    change: "변경",
    pick: "사진 고르기",
    pickHint: "사진이 없어요. 여기서 골라 주세요.",
    registeredHint: "이 사진이 컨셉 생성에 자동으로 사용돼요.",
    partner: "상대 사진",
    partnerPick: "상대 사진 고르기",
    partnerNeed: "커플 컨셉은 두 사람 사진이 다 있어야 해요.",
    artPhoto: "변환할 사진",
    artPick: "변환할 사진 고르기",
    artHint: "이 컨셉은 얼굴이 아니라 올린 사진 자체를 바꿔요. 한 번만 쓰고 지워요.",
    batchLabel: "장수",
    make: "만들기",
    credits: (n: number) => `${n} 크레딧`,
    makeWithCredits: (n: number) => `만들기 · ${n} 크레딧`,
    dress: {
      garmentLabel: "입어볼 의상 (한 번에 5장까지 선택)",
      addFirst: "의상 올리기",
      addMore: "더 추가",
      autoNote: "빠진 의상은 AI가 판단해서 생성해줘요.",
      needGarment: "입어볼 의상 사진을 먼저 올려주세요 🙂",
      styleLabel: "어떤 컷으로 만들까요?",
      mirror: "거울셀카",
      model: "일상컷",
    },
    fourcut: {
      countLabel: "컷 수",
      styleLabel: "스타일",
    },
    idphoto: {
      suitLabel: "정장 색상",
      bgLabel: "배경 색상",
      disclaimer: "AI로 생성된 증명사진이에요. 공공기관·여권·비자 심사 등 공식 제출용으로는 규격 불일치로 거절될 수 있으니 참고용으로 사용해 주세요.",
    },
  },
  batch: [
    { count: 1, cost: 1, label: "1장" },
    { count: 3, cost: 3, label: "3장" },
    { count: 6, cost: 5, label: "6장", badge: "17% 할인" },
    { count: 12, cost: 9, label: "12장", badge: "25% 할인" },
  ] as const,
  login: {
    title: "로그인",
    tagline: "상상이 현실이 되는 곳",
    apple: "Apple로 시작하기",
    kakao: "카카오로 시작하기",
    naver: "네이버로 시작하기",
    google: "Google로 시작하기",
    loading: "이동 중…",
    fail: "로그인에 실패했어요. 다시 시도해 주세요.",
    terms: "계속하면 이용약관과 개인정보처리방침에 동의한 것으로 봐요.",
    reasonMake: "만든 사진을 내 사진에 저장하려면 로그인이 필요해요",
    reasonFilter: "필터를 쓰려면 로그인이 필요해요",
    reasonCamera: "카메라를 쓰려면 로그인이 필요해요",
  },
  progress: {
    making: "이미지를 만들고 있어요",
    hint: "최대 몇 분까지 걸릴 수 있어요",
    hintBatch: (n: number) => `${n}장을 만드는 중이라 몇 분까지 걸릴 수 있어요`,
    safe: "앱을 닫아도 계속 만들어져요.\n다 되면 알림으로 알려드릴게요 🔔",
    resume: "연결이 잠시 끊겼지만 서버는 계속 만들고 있어요.\n결과를 기다리는 중이에요...",
    done: "완성!",
    fail: "생성 실패",
    open: "결과 보기",
    dismiss: "닫기",
    retry: "다시 시도",
    networkFail: "네트워크 요청에 실패했어요. 잠시 후 다시 시도해 주세요.",
    quota: "오늘 무료 횟수를 다 썼어요. 친구를 초대하면 크레딧을 받을 수 있어요 🙂",
  },
  result: {
    savedNote: "내 사진에 저장됐어요 · 앨범에도 저장",
    saveAlbum: "앨범에 저장",
    saved: "앨범에 저장했어요",
    saveFail: "앨범 저장에 실패했어요",
    edit: "다듬기",
    share: "공유",
    oneMore: "한 장 더",
    similar: "비슷한 컨셉",
  },
  photos: {
    title: "내 사진",
    empty: "아직 만든 사진이 없어요",
    emptyCta: "컨셉 고르러 가기",
    loginRequired: "로그인하면 내가 만든 사진을 볼 수 있어요",
    notice: "생성된 사진은 1시간만 보관돼요. 오래 보관하려면 앨범에 저장해 주세요.",
    deleteConfirm: "이 사진을 삭제할까요?",
    delete: "삭제",
    cancel: "취소",
    loadFail: "불러오기 실패",
  },
  profile: {
    title: "프로필",
    guestTitle: "로그인이 필요해요",
    guestDesc: "로그인하면 크레딧, 내 사진, 친구 초대를 이용할 수 있어요.",
    login: "로그인",
    credits: "크레딧",
    freeToday: "오늘 무료",
    unlimited: "무제한",
    store: "스토어",
    invite: "친구 초대",
    notify: "새 컨셉 알림 켜기",
    account: "계정",
    legal: "법적 고지",
    terms: "이용약관",
    privacy: "개인정보처리방침",
    logout: "로그아웃",
    deleteAccount: "계정 삭제",
    soon: "곧 열려요",
  },
  filter: {
    title: "필터",
    shoot: "카메라로 찍기",
    groups: { film: "필름", camera: "카메라", fun: "재미" },
    open: "편집기 열기",
  },
  camera: { title: "카메라" },
  editor: { title: "다듬기" },
  // 1.x Guide.jsx intro(guide.how.*) 문구 재사용 — 1장.
  guide: {
    title: "3단계면 끝나요",
    steps: [
      { t: "1. 컨셉 고르기", d: "매일 저녁 8시에 새 컨셉이 올라와요." },
      { t: "2. 사진 한 장 올리기", d: "얼굴이 잘 보이는 사진이면 충분해요." },
      { t: "3. 기다리기", d: "최대 몇 분 걸려요. 앱을 닫아도 계속 만들어지고, 다 되면 알려드려요." },
    ],
    cta: "시작하기",
  },
  store: {
    title: "충전하기",
    intro: (n: number) => `하루 무료 ${n}장을 모두 사용했어요. 크레딧 1장으로 이미지 한 장을 만들 수 있어요.`,
    held: (credits: number) => `현재 보유: ${credits}크레딧`,
    count: (n: number) => `${n}장`,
    per: (price: string) => `장당 ${price}`,
    pay: "구매하기",
    paying: "처리 중…",
    note: "구매는 Google Play 계정으로 안전하게 결제돼요.",
    restore: "구매 복원",
    restoring: "복원 중…",
    restoreOk: "구매 내역을 복원했어요.",
    restoreFail: "복원할 구매 내역을 찾지 못했어요.",
    badge: { first: "첫 구매", best: "베스트 가치", cheapest: "장당 최저", popular: "가장 인기" },
    subTitle: "rimikimi+",
    subDesc: "광고 없음 · 워터마크 없음 · 크레딧 자동 충전",
    subLegal: "구독은 표시된 기간마다 자동 갱신되며 Google Play 계정으로 결제돼요. 기간 종료 24시간 전까지 해지하지 않으면 갱신돼요. Google Play 설정에서 언제든 관리·해지할 수 있어요.",
    packDone: (n: number) => `크레딧 ${n}개가 충전됐어요! 🎉`,
    subDone: "rimikimi+ 구독 완료! 크레딧이 곧 충전되고 광고가 사라져요 ✨",
    unavailable: "결제를 사용할 수 없어요.",
    noProduct: "스토어 상품을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    grantLate: "구매 반영이 조금 늦어지고 있어요. 잠시 후 자동으로 들어와요.",
    needLogin: "로그인이 필요해요.",
    notConfigured: "스토어가 아직 준비되지 않았어요.",
  },
  creditSheet: {
    title: "크레딧이 부족해요",
    desc: (need: number) => `이 생성에는 ${need} 크레딧이 필요해요.`,
    inviteTitle: "친구 초대로 무료 3장",
    inviteDesc: "친구가 내 코드로 가입하면 크레딧 3개",
    resume: "구매하면 하던 생성이 바로 이어져요.",
  },
  invite: {
    title: "친구 초대하면 크레딧 3개",
    desc: "친구가 내 코드로 시작하면 두 사람 모두 크레딧을 받아요.",
    myCode: "내 초대 코드",
    tapToCopy: "탭해서 복사",
    codeCopied: "초대 코드를 복사했어요",
    enterCode: "친구 초대 코드 입력",
    codeApply: "등록",
    codeOk: "초대가 등록됐어요! 친구에게 크레딧 3개가 쌓였어요 🎉",
    share: "공유하기",
    shareText: (code: string, url: string) => `내 얼굴로 인생 프로필 만들기 ✨ rimikimi 같이 해요! 초대 코드: ${code}\n${url}`,
    fail: {
      invalid_code: "코드를 다시 확인해 주세요",
      code_not_found: "없는 코드예요",
      invalid_ref: "코드를 다시 확인해 주세요",
      self_referral: "내 코드는 등록할 수 없어요",
      already_referred: "이미 초대 코드를 등록했어요",
      ref_not_found: "없는 코드예요",
      db_error: "잠시 후 다시 시도해 주세요",
    } as Record<string, string>,
    cardTitle: "첫 사진, 완성했어요 🎉",
    cardDesc: "친구를 초대하면 크레딧 3개를 더 받아요.",
    cardCta: "초대 코드 보기",
  },
  account: {
    deleteConfirm: "정말 계정을 삭제할까요?\n생성한 이미지·크레딧·모든 데이터가 영구 삭제되며 되돌릴 수 없어요.",
    deleteDone: "계정이 삭제됐어요. 그동안 이용해 주셔서 감사합니다.",
    deleteFail: "계정 삭제에 실패했어요.",
    faceProfile: "페이스 프로필",
    faceOn: "등록됨 · 생성 때 얼굴 참조로 함께 보내요",
    faceOff: "없음 · 등록된 내 사진으로 만들 수 있어요",
    faceMake: "등록 사진으로 만들기",
    faceDelete: "삭제",
    faceNote: "얼굴은 내 폰에만 저장돼요. 생성할 때만 참조로 보내고 서버에 남기지 않아요.",
    faceNeedPhoto: "먼저 내 사진을 등록해 주세요.",
    faceFail: "기준 사진을 만들지 못했어요. 잠시 뒤 다시 시도해 주세요.",
  },
  notify: {
    toggle: "새 컨셉 알림 켜기",
    desc: "매일 저녁 8시 새 컨셉 · 생성 완료를 알려드려요",
    denied: "알림이 꺼져 있어요. 시스템 설정에서 켜 주세요.",
    dropTitle: "새로운 컨셉이 도착했어요 ✨",
    dropBody: (n: number, titles: string) => (titles ? `오늘의 새 컨셉 ${n}종 · ${titles}` : `오늘의 새 컨셉 ${n}종이 올라왔어요`),
  },
  fit: {
    title: "정방향으로 맞출까요?",
    desc: "이 사진은 3:4 비율이 아니에요. 세로로 바로 세우고 비율을 맞추면 컨셉과 편집기에서 더 잘 나와요.",
    crop: "잘라 맞춤 · 무료",
    cropHint: "얼굴 기준으로 3:4 크롭",
    outpaint: "채워 맞춤 · 1 크레딧",
    outpaintHint: "원본 픽셀은 그대로, 바깥을 채워요",
    skip: "그대로 두기",
    soon: "채워 맞춤은 곧 열려요",
    done: "3:4 로 맞췄어요",
  },
  common: { back: "뒤로", close: "닫기", retry: "다시 시도", loading: "불러오는 중..." },
} as const;
