// UI 문구 — 한국어(copyKo) + 영어(copyEn), 같은 모양의 두 표.
// 한국어: SPEC §2·§3 의 문구와 웹 src/i18nStrings.js(ko) 에서 가져온 것.
// 영어: 웹 src/i18nStrings.js(en) 에 같은 뜻의 문구가 있으면 그대로 재사용.
// 세 플랫폼이 같은 문구를 써야 하므로(SPEC §6-6) 화면 코드에 리터럴을 쓰지 않는다.
// 언어는 앱 시작 때 한 번 정한다(src/lib/locale.ts — 기기 첫 선호 언어가 ko 면 한국어, 아니면 영어).
// 호출부는 그대로 `copy.xxx` 를 쓴다.

import { isKo } from "./locale";

const copyKo = {
  tabs: {
    gallery: "갤러리",
    filter: "필터",
    camera: "카메라",
    photos: "내 사진",
    profile: "프로필",
  },
  home: {
    featured: "추천",
    newest: "새로 나왔어요",
    all: "전체",
    more: "더보기",
    loadFail: "컨셉을 불러오지 못했어요",
  },
  options: {
    myPhoto: "내 사진",
    useRegistered: "등록된 사진 사용",
    change: "변경",
    pick: "사진 고르기",
    pickHint: "사진이 없어요. 여기서 골라 주세요.",
    registeredHint: "이 사진이 컨셉 생성에 자동으로 사용돼요.",
    partner: "상대 사진",
    partnerPick: "상대 사진 고르기",
    partnerNeed: "커플 컨셉은 두 사람 사진이 다 있어야 해요.",
    artPhoto: "변환할 사진",
    artPick: "변환할 사진 고르기",
    artHint: "이 컨셉은 얼굴이 아니라 올린 사진 자체를 바꿔요. 한 번만 쓰고 지워요.",
    batchLabel: "장수",
    make: "만들기",
    credits: (n: number) => `${n} 크레딧`,
    makeWithCredits: (n: number) => `만들기 · ${n} 크레딧`,
    dress: {
      garmentLabel: "입어볼 의상 (한 번에 5장까지 선택)",
      addFirst: "의상 올리기",
      addMore: "더 추가",
      autoNote: "빠진 의상은 AI가 판단해서 생성해줘요.",
      needGarment: "입어볼 의상 사진을 먼저 올려주세요 🙂",
      styleLabel: "어떤 컷으로 만들까요?",
      mirror: "거울셀카",
      model: "일상컷",
    },
    fourcut: {
      countLabel: "컷 수",
      styleLabel: "스타일",
    },
    idphoto: {
      suitLabel: "정장 색상",
      bgLabel: "배경 색상",
      disclaimer: "AI로 생성된 증명사진이에요. 공공기관·여권·비자 심사 등 공식 제출용으로는 규격 불일치로 거절될 수 있으니 참고용으로 사용해 주세요.",
    },
  },
  batch: [
    { count: 1, cost: 1, label: "1장" },
    { count: 3, cost: 3, label: "3장" },
    { count: 6, cost: 5, label: "6장", badge: "17% 할인" },
    { count: 12, cost: 9, label: "12장", badge: "25% 할인" },
  ] as const,
  login: {
    title: "로그인",
    tagline: "상상이 현실이 되는 곳",
    apple: "Apple로 시작하기",
    kakao: "카카오로 시작하기",
    naver: "네이버로 시작하기",
    google: "Google로 시작하기",
    loading: "이동 중…",
    fail: "로그인에 실패했어요. 다시 시도해 주세요.",
    terms: "계속하면 이용약관과 개인정보처리방침에 동의한 것으로 봐요.",
    reasonMake: "만든 사진을 내 사진에 저장하려면 로그인이 필요해요",
    reasonFilter: "필터를 쓰려면 로그인이 필요해요",
    reasonCamera: "카메라를 쓰려면 로그인이 필요해요",
  },
  progress: {
    making: "이미지를 만들고 있어요",
    hint: "최대 몇 분까지 걸릴 수 있어요",
    hintBatch: (n: number) => `${n}장을 만드는 중이라 몇 분까지 걸릴 수 있어요`,
    safe: "앱을 닫아도 계속 만들어져요.\n다 되면 알림으로 알려드릴게요 🔔",
    resume: "연결이 잠시 끊겼지만 서버는 계속 만들고 있어요.\n결과를 기다리는 중이에요...",
    done: "완성!",
    fail: "생성 실패",
    open: "결과 보기",
    dismiss: "닫기",
    retry: "다시 시도",
    networkFail: "네트워크 요청에 실패했어요. 잠시 후 다시 시도해 주세요.",
    quota: "오늘 무료 횟수를 다 썼어요. 친구를 초대하면 크레딧을 받을 수 있어요 🙂",
  },
  result: {
    savedNote: "내 사진에 저장됐어요 · 앨범에도 저장",
    saveAlbum: "앨범에 저장",
    saved: "앨범에 저장했어요",
    saveFail: "앨범 저장에 실패했어요",
    edit: "다듬기",
    share: "공유",
    oneMore: "한 장 더",
    similar: "비슷한 컨셉",
  },
  photos: {
    title: "내 사진",
    empty: "아직 만든 사진이 없어요",
    emptyCta: "컨셉 고르러 가기",
    loginRequired: "로그인하면 내가 만든 사진을 볼 수 있어요",
    notice: "생성된 사진은 24시간만 보관돼요. 오래 보관하려면 앨범에 저장해 주세요.",
    deleteConfirm: "이 사진을 삭제할까요?",
    delete: "삭제",
    cancel: "취소",
    loadFail: "불러오기 실패",
  },
  profile: {
    title: "프로필",
    guestTitle: "로그인이 필요해요",
    guestDesc: "로그인하면 크레딧, 내 사진, 친구 초대를 이용할 수 있어요.",
    login: "로그인",
    credits: "크레딧",
    freeToday: "오늘 무료",
    unlimited: "무제한",
    store: "스토어",
    invite: "친구 초대",
    notify: "새 컨셉 알림 켜기",
    account: "계정",
    legal: "법적 고지",
    terms: "이용약관",
    privacy: "개인정보처리방침",
    logout: "로그아웃",
    deleteAccount: "계정 삭제",
    soon: "곧 열려요",
  },
  filter: {
    title: "필터",
    shoot: "카메라로 찍기",
    groups: { phone: "폰카", film: "필름", camera: "카메라", fun: "재미" },
    open: "편집기 열기",
  },
  camera: { title: "카메라" },
  editor: { title: "다듬기" },
  // 1.x Guide.jsx intro(guide.how.*) 문구 재사용 — 1장.
  guide: {
    title: "3단계면 끝나요",
    steps: [
      { t: "1. 컨셉 고르기", d: "매일 저녁 8시에 새 컨셉이 올라와요." },
      { t: "2. 사진 한 장 올리기", d: "얼굴이 잘 보이는 사진이면 충분해요." },
      { t: "3. 기다리기", d: "최대 몇 분 걸려요. 앱을 닫아도 계속 만들어지고, 다 되면 알려드려요." },
    ],
    cta: "시작하기",
  },
  store: {
    title: "충전하기",
    intro: (n: number) => `하루 무료 ${n}장을 모두 사용했어요. 크레딧 1장으로 이미지 한 장을 만들 수 있어요.`,
    held: (credits: number) => `현재 보유: ${credits}크레딧`,
    count: (n: number) => `${n}장`,
    per: (price: string) => `장당 ${price}`,
    pay: "구매하기",
    paying: "처리 중…",
    note: "구매는 Google Play 계정으로 안전하게 결제돼요.",
    restore: "구매 복원",
    restoring: "복원 중…",
    restoreOk: "구매 내역을 복원했어요.",
    restoreFail: "복원할 구매 내역을 찾지 못했어요.",
    badge: { first: "첫 구매", best: "베스트 가치", cheapest: "장당 최저", popular: "가장 인기" },
    subTitle: "rimikimi+",
    subDesc: "광고 없음 · 워터마크 없음 · 크레딧 자동 충전",
    subLegal: "구독은 표시된 기간마다 자동 갱신되며 Google Play 계정으로 결제돼요. 기간 종료 24시간 전까지 해지하지 않으면 갱신돼요. Google Play 설정에서 언제든 관리·해지할 수 있어요.",
    packDone: (n: number) => `크레딧 ${n}개가 충전됐어요! 🎉`,
    subDone: "rimikimi+ 구독 완료! 크레딧이 곧 충전되고 광고가 사라져요 ✨",
    unavailable: "결제를 사용할 수 없어요.",
    noProduct: "스토어 상품을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    grantLate: "구매 반영이 조금 늦어지고 있어요. 잠시 후 자동으로 들어와요.",
    needLogin: "로그인이 필요해요.",
    notConfigured: "스토어가 아직 준비되지 않았어요.",
  },
  creditSheet: {
    title: "크레딧이 부족해요",
    desc: (need: number) => `이 생성에는 ${need} 크레딧이 필요해요.`,
    inviteTitle: "친구 초대로 무료 3장",
    inviteDesc: "친구가 내 코드로 가입하면 크레딧 3개",
    resume: "구매하면 하던 생성이 바로 이어져요.",
  },
  invite: {
    title: "친구 초대하면 크레딧 3개",
    desc: "친구가 내 코드로 시작하면 두 사람 모두 크레딧을 받아요.",
    myCode: "내 초대 코드",
    tapToCopy: "탭해서 복사",
    codeCopied: "초대 코드를 복사했어요",
    enterCode: "친구 초대 코드 입력",
    codeApply: "등록",
    codeOk: "초대가 등록됐어요! 친구에게 크레딧 3개가 쌓였어요 🎉",
    share: "공유하기",
    shareText: (code: string, url: string) => `내 얼굴로 인생 프로필 만들기 ✨ rimikimi 같이 해요! 초대 코드: ${code}\n${url}`,
    fail: {
      invalid_code: "코드를 다시 확인해 주세요",
      code_not_found: "없는 코드예요",
      invalid_ref: "코드를 다시 확인해 주세요",
      self_referral: "내 코드는 등록할 수 없어요",
      already_referred: "이미 초대 코드를 등록했어요",
      ref_not_found: "없는 코드예요",
      db_error: "잠시 후 다시 시도해 주세요",
    } as Record<string, string>,
    cardTitle: "첫 사진, 완성했어요 🎉",
    cardDesc: "친구를 초대하면 크레딧 3개를 더 받아요.",
    cardCta: "초대 코드 보기",
  },
  account: {
    deleteConfirm: "정말 계정을 삭제할까요?\n생성한 이미지·크레딧·모든 데이터가 영구 삭제되며 되돌릴 수 없어요.",
    deleteDone: "계정이 삭제됐어요. 그동안 이용해 주셔서 감사합니다.",
    deleteFail: "계정 삭제에 실패했어요.",
    faceProfile: "페이스 프로필",
    faceOn: "등록됨 · 생성 때 얼굴 참조로 함께 보내요",
    faceOff: "없음 · 등록된 내 사진으로 만들 수 있어요",
    faceMake: "등록 사진으로 만들기",
    faceDelete: "삭제",
    faceNote: "얼굴은 내 폰에만 저장돼요. 생성할 때만 참조로 보내고 서버에 남기지 않아요.",
    faceNeedPhoto: "먼저 내 사진을 등록해 주세요.",
    faceFail: "기준 사진을 만들지 못했어요. 잠시 뒤 다시 시도해 주세요.",
  },
  notify: {
    toggle: "새 컨셉 알림 켜기",
    desc: "매일 저녁 8시 새 컨셉 · 생성 완료를 알려드려요",
    denied: "알림이 꺼져 있어요. 시스템 설정에서 켜 주세요.",
    dropTitle: "새로운 컨셉이 도착했어요 ✨",
    dropBody: (n: number, titles: string) => (titles ? `오늘의 새 컨셉 ${n}종 · ${titles}` : `오늘의 새 컨셉 ${n}종이 올라왔어요`),
  },
  fit: {
    title: "정방향으로 맞출까요?",
    desc: "이 사진은 3:4 비율이 아니에요. 세로로 바로 세우고 비율을 맞추면 컨셉과 편집기에서 더 잘 나와요.",
    crop: "잘라 맞춤 · 무료",
    cropHint: "얼굴 기준으로 3:4 크롭",
    outpaint: "채워 맞춤 · 1 크레딧",
    outpaintHint: "원본 픽셀은 그대로, 바깥을 채워요",
    skip: "그대로 두기",
    soon: "채워 맞춤은 곧 열려요",
    done: "3:4 로 맞췄어요",
  },
  // ── 다국어화 때 화면·lib 코드의 리터럴을 옮겨 온 것(한국어 값은 원래 리터럴 그대로) ──
  units: {
    photos: (n: number) => `${n}장`,
  },
  ui: {
    favorite: "즐겨찾기",
    unfavorite: "즐겨찾기 해제",
    generated: "이미 만든 컨셉",
    generatedShort: "만든 컨셉",
    creditsA11y: (label: string) => `크레딧 ${label}`,
    removeGarment: "의상 삭제",
    photo: "사진",
    loadFailTitle: "불러오지 못했어요",
    checkNetwork: "네트워크를 확인해 주세요.",
    makeThis: "이 컨셉으로 만들기",
    cuts: (n: number) => `${n}컷`,
    cropHintCenter: "가운데·위쪽 기준으로 3:4 크롭",
    notifChannel: "알림",
    openSettings: "설정 열기",
    allowPermission: "권한 허용",
    registered: "등록됨",
    none: "없음",
    registeredN: (n: number) => `${n}장 등록됨`,
    rescan: "다시 스캔",
    faceScan: "얼굴 스캔",
    refund: "환불 정책",
    discount: (n: number) => ` · ${n}% 할인`,
    subCredits: (credits: number, period: "week" | "month" | "year") =>
      `크레딧 ${credits}장 / ${period === "week" ? "주" : period === "month" ? "월" : "년"}`,
  },
  filterTab: {
    etc: "기타",
    original: "원본",
    todayA11y: (name: string) => `오늘의 필터 ${name}`,
    today: (group: string) => `오늘의 필터 · ${group}`,
    tapToStart: "탭하면 이 필터로 바로 시작",
    upTo10: "한 번에 10장까지",
    free: "전부 무료",
    shootHint: "· 여러 장 찍고 한 번에 필터",
  },
  shoot: {
    savedN: (n: number) => `${n}장을 앨범에 저장했어요`,
    noAlbumPerm: "앨범 저장 권한이 없어요",
    permTitle: "카메라 권한이 필요해요",
    permDesc: "카메라를 켜면 여러 장을 찍어 한 번에 필터를 입힐 수 있어요.",
    zoom: (pct: number) => `줌 ${pct}%`,
    flashOff: "플래시 끄기",
    flashOn: "플래시 켜기",
    removeNth: (i: number) => `${i}번째 사진 지우기`,
    full: "10장을 다 찍었어요 · 완료를 눌러 주세요",
    hint: "여러 장 찍고 한 번에 필터를 입혀요 · 최대 10장",
    flip: "전후면 전환",
    shutter: "촬영",
    doneA11y: (n: number) => `완료 ${n}장`,
    done: (n: number) => `완료 ${n}`,
  },
  faceScan: {
    label: { front: "정면", side1: "옆모습 ①", side2: "옆모습 ②" },
    title: { front: "정면을 봐주세요", side1: "고개를 한쪽으로 천천히", side2: "이제 반대쪽으로" },
    hint: {
      front: "얼굴을 원 안에 꽉 채워 주세요",
      side1: "45도쯤 돌린 채로 셔터를 눌러 주세요",
      side2: "아까와 반대쪽으로 돌리고 눌러 주세요",
    },
    saveFail: "사진을 저장하지 못했어요",
    saveFailBody: "다시 찍어 주세요.",
    permTitle: "카메라 권한이 필요해요",
    permDesc: "얼굴을 스캔하려면 카메라 접근을 허용해 주세요.",
    confirmTitle: "이 얼굴을 사용할까요?",
    privacy: "이 사진들은 이 휴대폰 안에만 저장돼요.\n사진을 만들 때만 참조로 쓰이고 서버에 보관하지 않아요.",
    start: "이 얼굴로 시작하기",
    retake: "다시 찍기",
    light: "조명",
    lightA11y: "화면 조명",
  },
  appError: {
    title: "앱 설정이 비어 있어요",
    desc: "이 빌드에는 서버 주소나 키가 들어가지 않았어요. 이대로는 로그인도 생성도 되지 않아요.",
    envFail: "환경 설정을 읽지 못했어요.",
  },
  errors: {
    loginParse: "로그인 응답을 이해하지 못했어요.",
    emailExists: "이 이메일은 이미 다른 방법(구글·카카오·네이버·애플 중 하나)으로 가입돼 있어요.\n처음 가입할 때 쓴 방법으로 로그인해 주세요 🙂",
    needLogin: "로그인이 필요해요.",
    genFail: "이미지 생성에 실패했어요.",
    photoFormat: "사진 형식을 읽을 수 없어요.",
    network: "네트워크 오류",
    loadFail: "불러오기 실패",
    earnFail: "적립 실패",
    deleteFail: "삭제 실패",
    badResponse: (status: number) => `서버 응답을 읽을 수 없어요 (오류 ${status})`,
    outpaintFail: (status: number) => `채워 맞춤 실패 (오류 ${status})`,
    outpaintNoResult: "채워 맞춤 결과를 받지 못했어요.",
    genFailStatus: (status: number) => `이미지 생성 실패 (오류 ${status})`,
    detailPrefix: "\n\n[원문] ",
    noImage: "이미지 응답을 받지 못했어요. 다른 컨셉으로 시도해 주세요.",
    timeout: (label: string) => `${label} 응답이 없어요. 네트워크 확인 후 다시 시도해 주세요.`,
    payLogin: "결제 로그인",
    productQuery: "상품 조회",
    pay: "결제",
    noProductDetail: "상품 정보를 불러오지 못했어요. 네트워크 확인 후 다시 시도해 주세요.",
    noProducts: "스토어가 상품 0개를 반환",
  },
  common: { back: "뒤로", close: "닫기", retry: "다시 시도", loading: "불러오는 중..." },
} as const;

// ============================================================================
// 영어 — copyKo 와 같은 모양(타입으로 강제). 웹 i18nStrings.js(en) 문구를 우선 재사용.
// ============================================================================

/** `as const` 리터럴 타입을 넓힌 모양 — 영어 표가 한국어 표와 **같은 키·같은 함수 시그니처**를 갖게 강제한다. */
type Widen<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends boolean
      ? boolean
      : T extends (...a: infer A) => infer R
        ? (...a: A) => Widen<R>
        : T extends readonly (infer U)[]
          ? readonly Widen<U>[]
          : T extends object
            ? { readonly [K in keyof T]: Widen<T[K]> }
            : T;
export type Copy = Widen<typeof copyKo>;

/** 1 이면 단수, 아니면 복수. */
const pl = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;
const credits = (n: number) => pl(n, "credit", "credits");
const photos = (n: number) => pl(n, "photo", "photos");

const copyEn: Copy = {
  tabs: {
    gallery: "Gallery",
    filter: "Filter",
    camera: "Camera",
    photos: "My Photos",
    profile: "Profile",
  },
  home: {
    featured: "Featured",
    newest: "New Arrivals",
    all: "All",
    more: "More",
    loadFail: "Couldn't load concepts",
  },
  options: {
    myPhoto: "My photo",
    useRegistered: "Using your saved photo",
    change: "Change",
    pick: "Choose a photo",
    pickHint: "No photo yet. Choose one here.",
    registeredHint: "This photo is used automatically when creating.",
    partner: "Partner's photo",
    partnerPick: "Choose partner's photo",
    partnerNeed: "Couple concepts need a photo of each person.",
    artPhoto: "Photo to transform",
    artPick: "Choose a photo to transform",
    artHint: "This concept transforms the photo itself, not just your face. It's used once, then discarded.",
    batchLabel: "Photos",
    make: "Create",
    credits: (n: number) => credits(n),
    makeWithCredits: (n: number) => `Create · ${credits(n)}`,
    dress: {
      garmentLabel: "Items to try on (pick up to 5 at once)",
      addFirst: "Add item",
      addMore: "Add more",
      autoNote: "Anything missing, AI fills in to match.",
      needGarment: "Please add a clothing photo first 🙂",
      styleLabel: "Which cut?",
      mirror: "Mirror selfie",
      model: "Everyday cut",
    },
    fourcut: {
      countLabel: "Cuts",
      styleLabel: "Style",
    },
    idphoto: {
      suitLabel: "Suit color",
      bgLabel: "Background color",
      disclaimer: "This ID photo is AI-generated. It may not meet official size and format rules, so it could be rejected for government, passport, or visa use. Please use it for reference only.",
    },
  },
  batch: [
    { count: 1, cost: 1, label: "1 photo" },
    { count: 3, cost: 3, label: "3 photos" },
    { count: 6, cost: 5, label: "6 photos", badge: "17% off" },
    { count: 12, cost: 9, label: "12 photos", badge: "25% off" },
  ],
  login: {
    title: "Sign in",
    tagline: "Where imagination becomes real",
    apple: "Continue with Apple",
    kakao: "Continue with Kakao",
    naver: "Continue with Naver",
    google: "Continue with Google",
    loading: "Loading…",
    fail: "Sign-in failed. Please try again.",
    terms: "By continuing, you agree to our Terms of Service and Privacy Policy.",
    reasonMake: "Sign in to save your photos to My Photos",
    reasonFilter: "Sign in to use filters",
    reasonCamera: "Sign in to use the camera",
  },
  progress: {
    making: "Creating your image",
    hint: "This can take a few minutes",
    hintBatch: (n: number) => `Making ${photos(n)} — this can take a few minutes`,
    safe: "You can close the app — we'll keep going.\nWe'll notify you when it's ready 🔔",
    resume: "The connection dropped, but the server is still working.\nWaiting for your result...",
    done: "Done!",
    fail: "Generation failed",
    open: "View result",
    dismiss: "Close",
    retry: "Retry",
    networkFail: "Network request failed. Please try again shortly.",
    quota: "You've used today's free creations. Invite a friend to earn credits 🙂",
  },
  result: {
    savedNote: "Saved to My Photos · also save it to your album",
    saveAlbum: "Save to album",
    saved: "Saved to your album",
    saveFail: "Couldn't save to your album",
    edit: "Edit",
    share: "Share",
    oneMore: "One more",
    similar: "Similar concepts",
  },
  photos: {
    title: "My Photos",
    empty: "No photos yet",
    emptyCta: "Pick a concept",
    loginRequired: "Sign in to see the photos you've created",
    notice: "Photos are kept for 24 hours. Save them to your album to keep them.",
    deleteConfirm: "Delete this photo?",
    delete: "Delete",
    cancel: "Cancel",
    loadFail: "Couldn't load",
  },
  profile: {
    title: "Profile",
    guestTitle: "Sign in required",
    guestDesc: "Sign in to use credits, My Photos, and invite friends.",
    login: "Sign in",
    credits: "Credits",
    freeToday: "Free today",
    unlimited: "Unlimited",
    store: "Store",
    invite: "Invite friends",
    notify: "New concept alerts",
    account: "Account",
    legal: "Legal",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    logout: "Sign out",
    deleteAccount: "Delete account",
    soon: "Coming soon",
  },
  filter: {
    title: "Filter",
    shoot: "Take photos",
    groups: { phone: "Phone cam", film: "Film", camera: "Camera", fun: "Fun" },
    open: "Open editor",
  },
  camera: { title: "Camera" },
  editor: { title: "Edit" },
  guide: {
    title: "Three steps, that's it",
    steps: [
      { t: "1. Pick a concept", d: "New concepts drop every day." },
      { t: "2. Upload one photo", d: "Any photo where your face is clearly visible." },
      { t: "3. Wait", d: "It can take a few minutes. You can close the app — we'll notify you when it's ready." },
    ],
    cta: "Get started",
  },
  store: {
    title: "Top up",
    intro: (n: number) => `You've used today's free ${n === 1 ? "photo" : `${n} photos`}. 1 credit makes 1 photo.`,
    held: (c: number) => `You have ${credits(c)}`,
    count: (n: number) => photos(n),
    per: (price: string) => `${price} each`,
    pay: "Buy",
    paying: "Processing…",
    note: "Purchases are billed securely through your Google Play account.",
    restore: "Restore purchases",
    restoring: "Restoring…",
    restoreOk: "Purchases restored.",
    restoreFail: "No purchases found to restore.",
    badge: { first: "First purchase", best: "Best value", cheapest: "Lowest per photo", popular: "Most popular" },
    subTitle: "rimikimi+",
    subDesc: "No ads · No watermark · Credits refill automatically",
    subLegal: "Subscriptions renew automatically each period and are billed to your Google Play account. They renew unless you cancel at least 24 hours before the period ends. Manage or cancel anytime in Google Play settings.",
    packDone: (n: number) => `${credits(n)} added! 🎉`,
    subDone: "You're on rimikimi+! Credits are on the way and ads are gone ✨",
    unavailable: "Payments aren't available.",
    noProduct: "Couldn't load store products. Please try again in a moment.",
    grantLate: "Your purchase is taking a little longer to apply. It'll arrive automatically soon.",
    needLogin: "Please sign in.",
    notConfigured: "The store isn't ready yet.",
  },
  creditSheet: {
    title: "Not enough credits",
    desc: (need: number) => `This creation needs ${credits(need)}.`,
    inviteTitle: "Invite a friend, get 3 free",
    inviteDesc: "Get 3 credits when a friend signs up with your code",
    resume: "After you buy, your creation picks up right where it left off.",
  },
  invite: {
    title: "Invite a friend, get 3 credits",
    desc: "When a friend starts with your code, you both get credits.",
    myCode: "Your invite code",
    tapToCopy: "Tap to copy",
    codeCopied: "Invite code copied",
    enterCode: "Enter a friend's code",
    codeApply: "Apply",
    codeOk: "Invite registered — your friend got 3 credits 🎉",
    share: "Share",
    shareText: (code: string, url: string) => `Turn your face into a dream portrait ✨ Try rimikimi with me! Invite code: ${code}\n${url}`,
    fail: {
      invalid_code: "Please check the code",
      code_not_found: "That code doesn't exist",
      invalid_ref: "Please check the code",
      self_referral: "You can't use your own code",
      already_referred: "You've already used an invite code",
      ref_not_found: "That code doesn't exist",
      db_error: "Please try again in a moment",
    },
    cardTitle: "Your first photo is ready 🎉",
    cardDesc: "Invite friends to get 3 more credits.",
    cardCta: "See invite code",
  },
  account: {
    deleteConfirm: "Delete your account?\nAll your generated images, credits, and data will be permanently erased. This cannot be undone.",
    deleteDone: "Your account has been deleted. Thank you for using rimikimi.",
    deleteFail: "Couldn't delete your account.",
    faceProfile: "Face profile",
    faceOn: "Saved · used when creating",
    faceOff: "None · you can still create with your saved photo",
    faceMake: "Use saved photo",
    faceDelete: "Delete",
    faceNote: "Your face photos are stored only on this phone. They're sent as a reference only while creating and never stored on our servers.",
    faceNeedPhoto: "Add your photo first.",
    faceFail: "Couldn't make a reference photo. Please try again in a moment.",
  },
  notify: {
    toggle: "New concept alerts",
    desc: "New-concept alerts at 8 PM your time · we'll tell you when your photos are ready",
    denied: "Notifications are off. Turn them on in system settings.",
    dropTitle: "New concepts are here ✨",
    // 서버 드롭 목록의 제목은 한국어뿐이라 영어에서는 제목을 붙이지 않는다.
    dropBody: (n: number, _titles: string) => `${n} new ${n === 1 ? "concept" : "concepts"} just dropped`,
  },
  fit: {
    title: "Straighten this photo?",
    desc: "This photo isn't 3:4. Straightening it and fitting the ratio gives better results in concepts and the editor.",
    crop: "Crop to fit · Free",
    cropHint: "3:4 crop around your face",
    outpaint: "Fill to fit · 1 credit",
    outpaintHint: "Keeps every original pixel and fills in the edges",
    skip: "Keep as is",
    soon: "Fill to fit is coming soon",
    done: "Fitted to 3:4",
  },
  common: { back: "Back", close: "Close", retry: "Retry", loading: "Loading..." },
  units: {
    photos: (n: number) => photos(n),
  },
  ui: {
    favorite: "Favorite",
    unfavorite: "Remove from favorites",
    generated: "Already created",
    generatedShort: "Created",
    creditsA11y: (label: string) => `Credits ${label}`,
    removeGarment: "Remove item",
    photo: "Photo",
    loadFailTitle: "Couldn't load",
    checkNetwork: "Please check your network.",
    makeThis: "Create with this concept",
    cuts: (n: number) => `${n} cuts`,
    cropHintCenter: "3:4 crop from the center and top",
    notifChannel: "Notifications",
    openSettings: "Open Settings",
    allowPermission: "Allow access",
    registered: "Added",
    none: "None",
    registeredN: (n: number) => `${photos(n)} added`,
    rescan: "Scan again",
    faceScan: "Scan face",
    refund: "Refund Policy",
    discount: (n: number) => ` · ${n}% off`,
    subCredits: (c: number, period: "week" | "month" | "year") => `${credits(c)} / ${period}`,
  },
  filterTab: {
    etc: "Other",
    original: "Original",
    todayA11y: (name: string) => `Today's filter ${name}`,
    today: (group: string) => `Today's filter · ${group}`,
    tapToStart: "Tap to start with this filter",
    upTo10: "Up to 10 at once",
    free: "All free",
    shootHint: "· Shoot, then filter all",
  },
  shoot: {
    savedN: (n: number) => `Saved ${photos(n)} to your album`,
    noAlbumPerm: "No permission to save to your album",
    permTitle: "Camera access needed",
    permDesc: "Turn on the camera to shoot several photos and filter them all at once.",
    zoom: (pct: number) => `Zoom ${pct}%`,
    flashOff: "Flash off",
    flashOn: "Flash on",
    removeNth: (i: number) => `Remove photo ${i}`,
    full: "You've taken 10 · tap Done",
    hint: "Shoot several, filter them all at once · up to 10",
    flip: "Flip camera",
    shutter: "Shutter",
    doneA11y: (n: number) => `Done, ${photos(n)}`,
    done: (n: number) => `Done ${n}`,
  },
  faceScan: {
    label: { front: "Front", side1: "Side ①", side2: "Side ②" },
    title: { front: "Look straight ahead", side1: "Slowly turn your head to one side", side2: "Now the other side" },
    hint: {
      front: "Fill the circle with your face",
      side1: "Turn about 45° and press the shutter",
      side2: "Turn the opposite way and press",
    },
    saveFail: "Couldn't save the photos",
    saveFailBody: "Please take them again.",
    permTitle: "Camera access needed",
    permDesc: "Allow camera access to scan your face.",
    confirmTitle: "Use this face?",
    privacy: "These photos are stored only on this phone.\nThey're sent as a reference only while creating and never stored on our servers.",
    start: "Start with this face",
    retake: "Retake",
    light: "Light",
    lightA11y: "Screen light",
  },
  appError: {
    title: "App settings are missing",
    desc: "This build doesn't include the server address or keys. Sign-in and creating won't work as is.",
    envFail: "Couldn't read the app settings.",
  },
  errors: {
    loginParse: "Couldn't understand the sign-in response.",
    emailExists: "This email is already registered with another sign-in method (Google, Kakao, Naver, or Apple).\nPlease sign in with the method you used first 🙂",
    needLogin: "Please sign in.",
    genFail: "Couldn't create the image.",
    photoFormat: "Couldn't read this photo format.",
    network: "Network error",
    loadFail: "Couldn't load",
    earnFail: "Couldn't add credits",
    deleteFail: "Couldn't delete",
    badResponse: (status: number) => `Couldn't read the server response (error ${status})`,
    outpaintFail: (status: number) => `Fill to fit failed (error ${status})`,
    outpaintNoResult: "Didn't get a Fill to fit result.",
    genFailStatus: (status: number) => `Image generation failed (error ${status})`,
    detailPrefix: "\n\n[Details] ",
    noImage: "Didn't get an image back. Please try another concept.",
    timeout: (label: string) => `${label} didn't respond. Check your network and try again.`,
    payLogin: "Payment sign-in",
    productQuery: "Product lookup",
    pay: "Payment",
    noProductDetail: "Couldn't load product info. Check your network and try again.",
    noProducts: "Store returned 0 products",
  },
};

export const copy: Copy = isKo ? copyKo : copyEn;
