// 한국어 문구 — SPEC §2·§3 의 문구와 웹 src/i18nStrings.js(ko) 에서 가져온 것.
// 세 플랫폼이 같은 문구를 써야 하므로(SPEC §6-6) 화면 코드에 리터럴을 쓰지 않는다.

export const copy = {
  tabs: {
    gallery: "갤러리",
    filter: "필터",
    camera: "카메라",
    photos: "내 사진",
    profile: "프로필",
  },
  home: {
    featured: "추천",
    newest: "새로 나왔어요",
    all: "전체",
    more: "더보기",
    loadFail: "컨셉을 불러오지 못했어요",
  },
  options: {
    myPhoto: "내 사진",
    useRegistered: "등록된 사진 사용",
    change: "변경",
    pick: "사진 고르기",
    pickHint: "사진이 없어요. 여기서 골라 주세요.",
    registeredHint: "이 사진이 컨셉 생성에 자동으로 사용돼요.",
    partner: "상대 사진",
    partnerPick: "상대 사진 고르기",
    partnerNeed: "커플 컨셉은 두 사람 사진이 다 있어야 해요.",
    artPhoto: "변환할 사진",
    artPick: "변환할 사진 고르기",
    artHint: "이 컨셉은 얼굴이 아니라 올린 사진 자체를 바꿔요. 한 번만 쓰고 지워요.",
    batchLabel: "장수",
    make: "만들기",
    credits: (n: number) => `${n} 크레딧`,
    makeWithCredits: (n: number) => `만들기 · ${n} 크레딧`,
    dress: {
      garmentLabel: "입어볼 의상 (한 번에 5장까지 선택)",
      addFirst: "의상 올리기",
      addMore: "더 추가",
      autoNote: "빠진 의상은 AI가 판단해서 생성해줘요.",
      needGarment: "입어볼 의상 사진을 먼저 올려주세요 🙂",
      styleLabel: "어떤 컷으로 만들까요?",
      mirror: "거울셀카",
      model: "일상컷",
    },
    fourcut: {
      countLabel: "컷 수",
      styleLabel: "스타일",
    },
  },
  batch: [
    { count: 1, cost: 1, label: "1장" },
    { count: 3, cost: 3, label: "3장" },
    { count: 6, cost: 5, label: "6장", badge: "17% 할인" },
    { count: 12, cost: 9, label: "12장", badge: "25% 할인" },
  ] as const,
  login: {
    title: "로그인",
    tagline: "상상이 현실이 되는 곳",
    apple: "Apple로 시작하기",
    kakao: "카카오로 시작하기",
    naver: "네이버로 시작하기",
    google: "Google로 시작하기",
    loading: "이동 중…",
    fail: "로그인에 실패했어요. 다시 시도해 주세요.",
    terms: "계속하면 이용약관과 개인정보처리방침에 동의한 것으로 봐요.",
    reasonMake: "만든 사진을 내 사진에 저장하려면 로그인이 필요해요",
    reasonFilter: "필터를 쓰려면 로그인이 필요해요",
    reasonCamera: "카메라를 쓰려면 로그인이 필요해요",
  },
  progress: {
    making: "이미지를 만들고 있어요",
    hint: "최대 몇 분까지 걸릴 수 있어요",
    hintBatch: (n: number) => `${n}장을 만드는 중이라 몇 분까지 걸릴 수 있어요`,
    safe: "앱을 닫아도 계속 만들어져요.\n다 되면 알림으로 알려드릴게요 🔔",
    resume: "연결이 잠시 끊겼지만 서버는 계속 만들고 있어요.\n결과를 기다리는 중이에요...",
    done: "완성!",
    fail: "생성 실패",
    open: "결과 보기",
    dismiss: "닫기",
    retry: "다시 시도",
    networkFail: "네트워크 요청에 실패했어요. 잠시 후 다시 시도해 주세요.",
    quota: "오늘 무료 횟수를 다 썼어요. 친구를 초대하면 크레딧을 받을 수 있어요 🙂",
  },
  result: {
    savedNote: "내 사진에 저장됐어요 · 앨범에도 저장",
    saveAlbum: "앨범에 저장",
    saved: "앨범에 저장했어요",
    saveFail: "앨범 저장에 실패했어요",
    edit: "다듬기",
    share: "공유",
    oneMore: "한 장 더",
    similar: "비슷한 컨셉",
  },
  photos: {
    title: "내 사진",
    empty: "아직 만든 사진이 없어요",
    emptyCta: "컨셉 고르러 가기",
    loginRequired: "로그인하면 내가 만든 사진을 볼 수 있어요",
    notice: "생성된 사진은 1시간만 보관돼요. 오래 보관하려면 앨범에 저장해 주세요.",
    deleteConfirm: "이 사진을 삭제할까요?",
    delete: "삭제",
    cancel: "취소",
    loadFail: "불러오기 실패",
  },
  profile: {
    title: "프로필",
    guestTitle: "로그인이 필요해요",
    guestDesc: "로그인하면 크레딧, 내 사진, 친구 초대를 이용할 수 있어요.",
    login: "로그인",
    credits: "크레딧",
    freeToday: "오늘 무료",
    unlimited: "무제한",
    store: "스토어",
    invite: "친구 초대",
    notify: "새 컨셉 알림 켜기",
    account: "계정",
    legal: "법적 고지",
    terms: "이용약관",
    privacy: "개인정보처리방침",
    logout: "로그아웃",
    deleteAccount: "계정 삭제",
    soon: "곧 열려요",
  },
  filter: {
    title: "필터",
    shoot: "카메라로 찍기",
    groups: { film: "필름", camera: "카메라", fun: "재미" },
    open: "편집기 열기",
  },
  camera: { title: "카메라" },
  editor: { title: "다듬기" },
  guide: {
    title: "컨셉을 고르고, 만들기만 누르세요",
    body: "내 사진은 한 번만 등록하면 돼요. 완성되면 내 사진에 저장되고 알림으로 알려드려요.",
    cta: "시작하기",
  },
  common: { back: "뒤로", close: "닫기", retry: "다시 시도", loading: "불러오는 중..." },
} as const;
